"""Compact SMILES set-cover drawn from Domalski--Hearing Tables 4--54.

Each tuple is ``(SMILES, paper compound name, article page)``.  The list was
reduced greedily only to avoid repeating hundreds of homologues in tests; the
source names and pages remain here so every exercised group is auditable.
"""

TABLE_EXAMPLES = (
    ('CC(C(=O)NC(CC1=CC=CC=C1)C(=O)O)NC(=O)CN', 'Glycylalanylphenylalanine', 1021),
    ('C=C1CC2CCC1C2', '2-Methylenebicyclo[2.2.1]heptane', 904),
    ('CCOC(=O)CCC#C', 'Ethyl-4-pentynoate', 972),
    ('C1=CC=C(C=C1)/C=C/S(=O)(=O)C2=CC=CC=C2', 'trans-Phenyl beta-styryl sulfone', 1054),
    ('C1=CC=C(C(=C1)C(=O)O)O', '2-Hydroxybenzoic acid', 961),
    ('C/C=C/C(=O)OC', 'Methyl crotonate', 971),
    ('CNC(=O)N', 'Methylurea', 1011),
    ('C1=CC2=C3C(=C1)C4=CC=CC5=C4C(=CC=C5)C3=CC=C2', 'Perylene', 886),
    ('CC(C)OC(C)(C)C', 'Isopropyl tert-butyl ether', 929),
    ('CC(C)C(=O)C', '3-Methyl-2-butanone', 940),
    ('CCCCC(C)OO', 'n-Hexyl-2-hydroperoxide', 979),
    ('CCNC1=CC=CC=C1', 'N-Ethylaniline', 990),
    ('CC(C)(C)CC(C)(C)N=NC(C)(C)C', 'tert-Butyl-(1,1,3,3-tetramethylbutyl)diazene', 999),
    ('CCSC', 'Ethyl methyl sulfide', 1041),
    ('CCS(=O)CC=C', 'Allyl ethyl sulfoxide', 1049),
    ('CCS(=O)(=O)C', 'Ethyl methyl sulfone', 1050),
    ('C(C(C(F)(F)F)(F)F)O', '2,2,3,3,3-Pentafluoro-1-propanol', 1064),
    ('CC(C(C=O)(Cl)Cl)Cl', '2,2,3-Trichlorobutanal', 1081),
    ('C=COCCCl', '2-Chloroethyl vinyl ether', 1081),
    ('CC(=C)C=C', '2-Methyl-1,3-butadiene', 857),
    ('C#CC1=CC=CC=C1', 'Ethynylbenzene', 874),
    ('CC(C)C1=CC=C(C=C1)C2=CC=CC=C2', 'Isopropylbiphenyl', 879),
    ('CC(C)(C)C(=O)OC(=O)C(C)(C)C', '2,2-Dimethylpropanoic anhydride', 964),
    ('CC(C)NC(C)C', 'Diisopropylamine', 986),
    ('C1=CC=C(C=C1)CN(CC2=CC=CC=C2)CC3=CC=CC=C3', 'Tribenzylamine', 988),
    ('CNN', 'Methylhydrazine', 997),
    ('C1=CC=C(C=C1)N=NC2=CC=CC=C2', 'trans-Azobenzene', 999),
    ('CN(C)C=O', 'N,N-Dimethylmethanamide', 1008),
    ('C1=CC=C(C(=C1)N)[N+](=O)[O-]', '2-Nitroaniline', 1028),
    ('C(N[N+](=O)[O-])N[N+](=O)[O-]', 'Methylenedinitramine', 1033),
    ('CCC(C)S', '2-Butanethiol', 1038),
    ('C1=CC=C(C=C1)S', 'Benzenethiol', 1041),
    ('CC(C)(C)SCC=C', 'Allyl tert-butyl sulfide', 1047),
    ('C1=CC=C(C=C1)S(=O)C2=CC=CC=C2', 'Diphenyl sulfoxide', 1050),
    ('C#CCS(=O)(=O)C1=CC=CC=C1', '2-(Propynylsulfonyl)benzene', 1052),
    ('COS(=O)OC', 'Dimethyl sulfite', 1055),
    ('CCCCOS(=O)(=O)OCCCC', 'Di-n-butyl sulfate', 1055),
    ('C1CSC=C1', '2,3-Dihydrothiophene', 1058),
    ('FCC(F)F', '1,1,2-Trifluoroethane', 1059),
    ('C(=C(F)F)F', 'Trifluoroethylene', 1060),
    ('C1(=C(C(=C(C(=C1F)F)F)F)F)C(F)(F)F', 'Pentafluoro(trifluoromethyl)benzene', 1060),
    ('C(C(Cl)(Cl)Cl)(Cl)Cl', 'Pentachloroethane', 1070),
    ('C1=CC(=CC(=C1)Cl)C=O', '3-Chlorobenzaldehyde', 1080),
    ('C(C(=O)Cl)(Cl)Cl', 'Dichloroacetyl chloride', 1084),
    ('CCC(CBr)Br', '1,2-Dibromobutane', 1088),
    ('CCC(CI)I', '1,2-Diiodobutane', 1094),
    ('C(C(F)(Cl)Cl)(F)(F)Cl', '1,1,2-Trichloro-1,2,2-trifluoroethane', 1099),
    ('C', 'Methane', 830),
    ('CC/C=C\\C(C)(C)C', 'cis-2,2-Dimethyl-3-hexene', 854),
    ('CC(C)(C)C1=CC=CC=C1', 'tert-Butylbenzene', 873),
    ('CC(=C)C1=CC=CC=C1', 'Isopropenylbenzene', 874),
    ('C1=CC=C(C=C1)CC2=CC=CC=C2', 'Diphenylmethane', 875),
    ('C=C(C1=CC=CC=C1)C2=CC=CC=C2', '1,1-Diphenylethylene', 875),
    ('C1=CC=C(C=C1)C(C2=CC=CC=C2)C3=CC=CC=C3', 'Triphenylmethane', 876),
    ('C1=CC=C(C=C1)C(C2=CC=CC=C2)(C3=CC=CC=C3)C4=CC=CC=C4', 'Tetraphenylmethane', 876),
    ('C1C=C1', 'Cyclopropene', 889),
    ('C1C=CC2=CC=CC=C21', 'Indene', 902),
    ('C1C2C=CC1C=C2', 'Bicyclo[2.2.1]hepta-2,5-diene', 902),
    ('C=CCO', 'Allyl alcohol', 909),
    ('C1=CC=C(C=C1)CO', 'Benzyl alcohol', 914),
    ('CC(C)(C)O', 'tert-Butyl alcohol', 916),
    ('C1=CC=C(C=C1)C(C2=CC=CC=C2)(C3=CC=CC=C3)O', 'Triphenylmethanol', 917),
    ('C=COC=C', 'Divinyl ether', 929),
    ('COC(OC)OC', 'Trimethoxymethane', 929),
    ('CC(OC)OC', '1,1-Dimethoxyethane', 930),
    ('CC(C)(OC)OC', '2,2-Dimethoxypropane', 930),
    ('CCOCOCC', 'Diethoxymethane', 930),
    ('CC(OC)(OC)OC', '1,1,1-Trimethoxyethane', 930),
    ('COC(OC)(OC)OC', 'Tetramethyl orthocarbonate', 930),
    ('COC1=CC=CC=C1', 'Anisole', 934),
    ('C1=CC=C(C=C1)OC2=CC=CC=C2', 'Diphenyl ether', 935),
    ('C=O', 'Formaldehyde', 935),
    ('C(=O)C=O', 'Glyoxal', 935),
    ('C/C=C/C=O', 'Crotonaldehyde', 936),
    ('CC(=O)C(=O)C', 'Diacetyl', 942),
    ('CC(=O)CC(=O)C', '2,4-Pentanedione', 942),
    ('CC(=O)C1=CC=CC=C1', 'Acetophenone', 944),
    ('C1=CC=C(C=C1)C(=O)C2=CC=CC=C2', 'Benzophenone', 944),
    ('C1=CC=C(C=C1)C(=O)C(=O)C2=CC=CC=C2', 'Benzil', 945),
    ('C(=O)(C(=O)O)O', 'Oxalic acid', 951),
    ('C1=CC=C(C=C1)C(C(C2=CC=CC=C2)C(=O)O)C(=O)O', 'Diphenylsuccinic acid', 963),
    ('COC=O', 'Methyl formate', 966),
    ('CC(=O)OC=C', 'Vinyl acetate', 971),
    ('CCOC(=O)CC#CC', 'Ethyl-3-pentynoate', 972),
    ('CCOC(=O)C/C=C/C', 'Ethyl-3-pentenoate', 972),
    ('CC(=O)OC1=CC=CC=C1', 'Phenyl acetate', 976),
    ('CC(C)(C1=CC=CC=C1)OO', 'Cumyl hydroperoxide', 980),
    ('CCOC(=O)OCC', 'Diethyl carbonate', 982),
    ('CC(C)(C)N', 'tert-Butylamine', 984),
    ('C1=CC=C(C=C1)N(C2=CC=CC=C2)C3=CC=CC=C3', 'Triphenylamine', 988),
    ('CN(C1=CC=CC=C1)C2=CC=CC=C2', 'N-Methyldiphenylamine', 990),
    ('CCC#N', 'Propionitrile', 992),
    ('C=CC#N', 'Acrylonitrile', 994),
    ('CC(C)C#N', 'Isobutyronitrile', 994),
    ('CC=CCC#N', '3-Pentenenitrile', 995),
    ('C(#CC#N)C#N', '2-Butyne-1,4-dinitrile', 996),
    ('CN(C)N', '1,1-Dimethylhydrazine', 997),
    ('C1=CC=C(C=C1)NN', 'Phenylhydrazine', 998),
    ('CCN=NCC', 'Azoethane', 998),
    ('CC(C)N=NC(C)C', 'Azoisopropane', 999),
    ('C1CCC(CC1)N=[N+]=[N-]', 'Azidocyclohexane', 1000),
    ('C1=CC=C(C=C1)N=[N+]=[N-]', 'Phenyl azide', 1000),
    ('C1=CC=C(C=C1)CN=[N+]=[N-]', 'Benzyl azide', 1000),
    ('C1=CC=C(C=C1)C(C2=CC=CC=C2)(C3=CC=CC=C3)N=[N+]=[N-]', 'Triphenylmethyl azide', 1001),
    ('C1=CC=NC=C1', 'Pyridine', 1001),
    ('C1=CNC=C1', 'Pyrrole', 1002),
    ('CC(=O)NC1=CC=CC=C1', 'Acetanilide', 1010),
    ('CCCCN(C(=O)C)C(=O)C', 'N-Acetyl-N-butylacetamide', 1010),
    ('CC(=O)NC(=O)N', 'Acetylurea', 1014),
    ('C(C[C@@H](C(=O)O)N)CN', 'DL-Ornithine', 1017),
    ('C(CC(=O)N)[C@@H](C(=O)O)N', 'L-Glutamine', 1018),
    ('CN(C)N=O', 'Dimethylnitrosamine', 1021),
    ('C1=CC=C(C=C1)N=O', 'Nitrosobenzene', 1021),
    ('C[N+](=O)[O-]', 'Nitromethane', 1022),
    ('C([N+](=O)[O-])[N+](=O)[O-]', 'Dinitromethane', 1022),
    ('C([N+](=O)[O-])([N+](=O)[O-])[N+](=O)[O-]', 'Trinitromethane', 1022),
    ('C([N+](=O)[O-])([N+](=O)[O-])([N+](=O)[O-])[N+](=O)[O-]', 'Tetranitromethane', 1022),
    ('CC[N+](=O)[O-]', 'Nitroethane', 1023),
    ('CCC(C)[N+](=O)[O-]', '2-Nitrobutane', 1023),
    ('CC(C)(C)[N+](=O)[O-]', '2-Methyl-2-nitropropane', 1024),
    ('CC([N+](=O)[O-])[N+](=O)[O-]', '1,1-Dinitroethane', 1024),
    ('CC(C)([N+](=O)[O-])[N+](=O)[O-]', '2,2-Dinitropropane', 1025),
    ('C1=CC=C(C=C1)C[N+](=O)[O-]', 'Phenylnitromethane', 1026),
    ('CON=O', 'Methyl nitrite', 1031),
    ('CO[N+](=O)[O-]', 'Methyl nitrate', 1032),
    ('C1N(CN(CN1[N+](=O)[O-])[N+](=O)[O-])[N+](=O)[O-]', 'RDX', 1034),
    ('CN(C1=C(C=C(C=C1[N+](=O)[O-])[N+](=O)[O-])[N+](=O)[O-])[N+](=O)[O-]', 'Tetralite', 1034),
    ('C1=CC=C(C=C1)CS', 'Benzyl mercaptan', 1041),
    ('C1=CC=C(C=C1)SC2=CC=CC=C2', 'Diphenyl sulfide', 1047),
    ('CSC1=CC=CC=C1', 'Methyl phenyl sulfide', 1047),
    ('CSSC', 'Dimethyl disulfide', 1048),
    ('CS(=O)C', 'Dimethyl sulfoxide', 1049),
    ('CCS(=O)(=O)CC=C', 'Allyl ethyl sulfone', 1051),
    ('CC(C)S(=O)(=O)C', 'Isopropyl methyl sulfone', 1051),
    ('CC(C)(C)S(=O)(=O)C(C)(C)C', 'Di-tert-butyl sulfone', 1051),
    ('CS(=O)(=O)CC1=CC=CC=C1', 'Benzyl methyl sulfone', 1052),
    ('CC1=CC=C(C=C1)S(=O)(=O)C(=C)C', '1-Methyl-4-(1-methylethenylsulfonyl)benzene', 1053),
    ('C1=CC=C(C=C1)S(=O)(=O)C2=CC=CC=C2', 'Diphenyl sulfone', 1054),
    ('CF', 'Methyl fluoride', 1058),
    ('CC(C)F', '2-Fluoropropane', 1058),
    ('CCl', 'Methyl chloride', 1066),
    ('CC(C)(C)Cl', 'tert-Butyl chloride', 1068),
    ('C(=C(Cl)Cl)(Cl)Cl', 'Tetrachloroethylene', 1071),
    ('C=CCl', 'Vinyl chloride', 1071),
    ('CC(=C)Cl', '2-Chloro-1-propene', 1071),
    ('C1=CC=C(C=C1)CCl', 'Benzyl chloride', 1073),
    ('C(C(=O)O)Cl', 'Chloroacetic acid', 1079),
    ('CC(C(=O)O)Cl', '2-Chloropropanoic acid', 1079),
    ('C1=CC=C(C=C1)C(=O)Cl', 'Benzoyl chloride', 1084),
    ('CBr', 'Methyl bromide', 1086),
    ('CC(C)(C)Br', 'tert-Butyl bromide', 1088),
    ('C=CBr', 'Vinyl bromide', 1090),
    ('C1=CC=C(C=C1)CBr', 'Benzyl bromide', 1091),
    ('CC(=O)Br', 'Acetyl bromide', 1092),
    ('CI', 'Methyl iodide', 1092),
    ('CC(C)(C)I', 'tert-Butyl iodide', 1093),
    ('CC=CI', '1-Iodo-1-propene', 1094),
    ('CC#CI', '1-Iodopropyne', 1094),
    ('C1=CC=C(C=C1)I', 'Iodobenzene', 1094),
    ('C1=CC=C(C=C1)CI', 'Benzyl iodide', 1095),
    ('CC(F)Cl', '1-Chloro-1-fluoroethane', 1099),
    ('C(C(Cl)Br)(Cl)Br', '1,2-Dibromo-1,2-dichloroethane', 1099),
    ('C(C(F)(F)Br)(F)(F)Br', '1,2-Dibromotetrafluoroethane', 1099),
    ('C(C(C(F)(F)F)(Cl)Cl)Cl', '1,1,1-Trichloro-3,3,3-trifluoropropane', 1100),
    ('C(=C(F)Cl)(F)F', 'Chlorotrifluoroethylene', 1101),
    ('C1(=C(C(=C(C(=C1F)F)Br)F)F)F', 'Bromopentafluorobenzene', 1101),
)

# Rare/single-phase rows whose paper examples are not selected by the compact
# set cover above.  Keys make the intended Table-2 group explicit.
RARE_GROUP_EXAMPLES = {
    'C-(C)2(CB)2': 'CC(C)(c1ccccc1)c1ccccc1',
    'C-(C)(CB)3': ('C(c1ccccc1)(c2ccccc2)(c3ccccc3)'
                    'C(c4ccccc4)(c5ccccc5)c6ccccc6'),
    'O-(H)(Cd)': 'C=CO',
    'Cd-(I)2': 'C=C(I)I',
    'O-(SO)(H)': 'OS(=O)O',
    'SO2-(Ct)(CB)': 'Cc1ccc(S(=O)(=O)C#CC)cc1',
    'C-(Br)(Cl)(F)': 'FC(Cl)Br',
    'Cd-(C)(S)': 'CC(=C)S',
    'N-(CB)2(CO)': 'CC(=O)N(c1ccccc1)c1ccccc1',
    'Ct-(SO2)': 'Cc1ccc(S(=O)(=O)C#CC)cc1',
    'C-(C)2(I)2': 'CC(I)(I)C',
    'C-(H)(C)(CB)2': 'CC(c1ccccc1)c1ccccc1',
    'Cd-(O)(Cd)': 'C=C(OC)C=C',
    'Cd-(C)(CO)': 'CC(=C)C=O',
    'C-(H)2(I)(O)': 'ICO',
    'C-(C)(I)3': 'IC(I)(I)C',
    'Ct-(F)': 'C#CF',
    'Nr-(C)': 'CC=NC',
    'N-(C)2(CB)': 'CN(C)c1ccccc1',
    'C-(H)2(C)(N3)': 'CCN=[N+]=[N-]',
    'C-(H)(O)2(C)': 'COC(O)C',
    'C-(H)(O)(CO)(C)': 'CC(O)C(=O)O',
    'C-(H)(C)(Br)2': 'CC(Br)Br',
    'C-(H)(C)(I)2': 'IC(I)C',
    'Cd-(Cd)(CB)': 'C=C(C=C)c1ccccc1',
    'Cd-(Cl)(Br)': 'BrC(Cl)=C',
    'SO2-(C)(Cd)': 'C=CS(=O)(=O)C',
    'C-(H)2(CO)(Br)': 'BrCC=O',
    'N-(CB)2(N)': 'NN(c1ccccc1)c1ccccc1',
    'N-(C)(NO2)2': 'CN([N+](=O)[O-])[N+](=O)[O-]',
    'N-(H)(Cd)2': 'C=CN(C=C)',
    'S-(H)(CO)': 'CC(=O)S',
    'S-(H)(Cd)': 'C=CS',
    'N-(CO)2(N)': 'NC(=O)N(N)C(=O)N',
    'CO-(CB)(N)-amino-acid': 'NC(=O)c1ccccc1C(N)C(=O)O',
    'S-(Cd)2': 'C=CSC=C',
    'CO-(O)(CO)': 'COC(=O)C(=O)OC',
    'Ca': 'C=C=C',
    'CO-(C)(S)': 'CSC(=O)C',
    'N-(C)(F)2': 'CN(F)F',
    'C-(C)2(Br)2': 'CC(Br)(Br)C',
    'CO-(Cd)(N)': 'C=C(C(=O)N)',
    'C-(H)2(S)2': 'SCS',
    'C-(C)3(F)': 'CC(C)(C)F',
    'N-(C)(Cd)2': 'C=CN(C)C=C',
    'S-(CO)(C)': 'CSC(=O)C',
    'N-(C)(CB)(CO)': 'CC(=O)N(C)c1ccccc1',
    'C-(H)2(CO)(CB)': 'O=CCc1ccccc1',
    'C-(C)(Br)3': 'BrC(Br)(Br)C',
    'N-(CB)(CO)2': 'O=C1N(c2ccccc2)C(=O)CC1',
    'C-(C)(Br)2(F)': 'BrC(Br)(F)C',
    'Cd-(H)(N)': 'C=CN',
    'Cd-(Br)2': 'BrC(Br)=C',
    'S-(H)(S)': 'SS',
    'Ct-(Cd)': 'C#CC=C',
    'C-(H)(C)2(SO)': 'CC(C)S(=O)C',
    'SO-(C)(CB)': 'CS(=O)c1ccccc1',
    'N-(H)(CO)(NO2)': 'O=C(N[N+](=O)[O-])C',
    'C-(H)2(Ct)2': 'C#CC(C#C)',
    'C-(C)3(Ct)': 'CC(C)(C)C#C',
    'CO-(C)(Ct)': 'C#CC(=O)C',
    'C-(H)(C)(Cl)(O)': 'COC(Cl)C',
    'CO-(CB)(N)': 'NC(=O)c1ccccc1',
    'Ct-(Ct)': 'C#CC#C',
    'S-(S)2': 'SSS',
    'C-(H)(CO)(CB)2': 'O=CC(c1ccccc1)c1ccccc1',
    'Cd-(C)(N)': 'CC(=C)N',
    'C-(H)(C)(Cd)(SO2)': 'CC(C=C)S(=O)(=O)C',
    'Cd-(O)(C)': 'COC(C)=C',
    'Ct-(CO)': 'C#CC=O',
    'C-(H)3(CN)': 'CC#N',
    'O-(SO2)(H)': 'OS(=O)(=O)O',
    'N-(H)(CB)(NO2)': 'O=[N+]([O-])Nc1ccccc1',
    'Cd-(Br)(F)': 'BrC(F)=C',
    'Cd-(H)(N1)2': 'n1cncnc1',
    'NA-(oxide)(C)': 'CC(C)N=[N+]([O-])C(C)C',
    'CB-(CB)(CBF)2': 'C1=CC=C2C(=C1)C=C3C=CC=CC3=C2C4=C5C=CC=CC5=CC6=CC=CC=C64',
    'CB-(CB)2(CBF)': 'C1=CC=C2C(=C1)C=C(C3=CC=CC=C23)C4=CC5=CC=CC=C5C6=CC=CC=C64',
}
