"""Published-parameter PSRK equation-of-state implementation.

The numerical kernel accepts components by CAS number and uses the published
2005 PSRK JSON parameter tables in ``data/psrk``. It implements the original
PSRK equation of state without volume translation, with resolver-backed
critical-property fallbacks supplied explicitly by the integration layer.

References
----------
T. Holderbaum and J. Gmehling, Fluid Phase Equilibria 70 (1991) 251-265.
S. Horstmann et al., Fluid Phase Equilibria 227 (2005) 157-164.
"""

from __future__ import annotations

import json
import math
from dataclasses import dataclass
from functools import lru_cache
from pathlib import Path
from typing import Any, Mapping, Sequence

from .ge_eos import (
    ExcessGibbsState,
    ModifiedHuronVidalFirstOrderMixingRule,
)


if __package__ and __package__.split('.', 1)[0] == 'pfdsim':
    from ..physical_constants import R_BAR_CM3_MOL_K
else:
    from physical_constants import R_BAR_CM3_MOL_K

R_BAR_CM3_PER_MOL_K = R_BAR_CM3_MOL_K
PSRK_Q1 = -0.64663
SRK_OMEGA_A = 0.42748
SRK_OMEGA_B = 0.08664
UNIFAC_COORDINATION_NUMBER = 10.0

_DATA_DIR = Path(__file__).resolve().parent.parent / "data" / "psrk"
_DEFAULT_GROUP_DATA = _DATA_DIR / "group_parameters.json"
_DEFAULT_PURE_DATA = _DATA_DIR / "pure_components.json"


class PSRKError(RuntimeError):
    """Base error for PSRK calculations."""


class PSRKDataError(PSRKError):
    """Raised when a JSON parameter table is invalid or incomplete."""


class PSRKUnsupportedComponentError(PSRKError):
    """Raised when a component cannot be represented by the current data policy."""


class PSRKCalculationError(PSRKError):
    """Raised when a requested PSRK state cannot be evaluated."""


@dataclass(frozen=True)
class _Subgroup:
    subgroup_id: int
    main_group_id: int
    R: float
    Q: float


@dataclass(frozen=True)
class _Component:
    cas: str
    name: str
    Tc_K: float
    Pc_bar: float
    omega: float
    uses_mathias_copeman: bool
    c1: float
    c2: float
    c3: float
    Tmin_K: float | None
    Tmax_K: float | None
    subgroups: tuple[tuple[int, int], ...]
    r: float
    q: float
    a0: float
    b: float
    parameter_source: str


@dataclass(frozen=True)
class _MixtureParameters:
    composition: tuple[float, ...]
    pure_a: tuple[float, ...]
    pure_d: tuple[float, ...]
    b: float
    D: float
    dD_dT: float
    sigma: tuple[float, ...]


@lru_cache(maxsize=8)
def _read_json(path_text: str) -> dict:
    path = Path(path_text)
    try:
        payload = json.loads(path.read_text(encoding="utf-8"))
    except OSError as error:
        raise PSRKDataError(f"Unable to read PSRK data file {path}: {error}") from error
    except json.JSONDecodeError as error:
        raise PSRKDataError(f"Invalid JSON in PSRK data file {path}: {error}") from error
    if not isinstance(payload, dict):
        raise PSRKDataError(f"PSRK data file {path} must contain a JSON object")
    return payload


def _positive_finite(value: object, context: str) -> float:
    try:
        result = float(value)
    except (TypeError, ValueError) as error:
        raise PSRKDataError(f"{context} must be numeric") from error
    if not math.isfinite(result) or result <= 0.0:
        raise PSRKDataError(f"{context} must be positive and finite")
    return result


def _finite(value: object, context: str) -> float:
    try:
        result = float(value)
    except (TypeError, ValueError) as error:
        raise PSRKDataError(f"{context} must be numeric") from error
    if not math.isfinite(result):
        raise PSRKDataError(f"{context} must be finite")
    return result


class PSRK:
    """Original PSRK EOS for JSON-tabulated CAS-number components.

    Parameters
    ----------
    components:
        Unique CAS numbers defining the fixed component order.
    component_fallbacks:
        Optional CAS-keyed resolved parameters. A fallback record requires
        ``Tc_K``, ``Pc_bar``, and ``omega``. It is used when either published
        PSRK critical is estimated, or when ``override_bundle`` is true.
        Optional ``mc_c1``/``mc_c2``/``mc_c3`` values replace generalized
        Soave alpha for an explicit bundle override.
    group_data_path, pure_data_path:
        Optional alternate files using the schemas generated by
        ``scripts/convert_psrk2005_supplement.py``.

    Notes
    -----
    A complete published subgroup assignment is always required. Unstarred
    PSRK criticals and Mathias-Copeman coefficients are used as one bundle;
    otherwise an explicit fallback uses resolved criticals and generalized
    Soave alpha. Temperatures and pressures use kelvin and bar.
    """

    def __init__(
        self,
        components: Sequence[str],
        *,
        component_fallbacks: Mapping[str, Mapping[str, Any]] | None = None,
        group_data_path: str | Path = _DEFAULT_GROUP_DATA,
        pure_data_path: str | Path = _DEFAULT_PURE_DATA,
    ) -> None:
        component_ids = tuple(str(component).strip() for component in components)
        if not component_ids:
            raise PSRKUnsupportedComponentError("PSRK requires at least one component")
        if any(not component for component in component_ids):
            raise PSRKUnsupportedComponentError("PSRK component CAS numbers cannot be blank")
        if len(component_ids) != len(set(component_ids)):
            raise PSRKUnsupportedComponentError("PSRK component CAS numbers must be unique")

        self.warnings: list[str] = []
        self._warning_keys: set[str] = set()
        self._phi_phi_k_cache: dict[tuple, dict[str, float]] = {}
        self._mixing_rule = ModifiedHuronVidalFirstOrderMixingRule(PSRK_Q1)
        fallbacks = {
            str(cas).strip(): dict(values)
            for cas, values in (component_fallbacks or {}).items()
            if isinstance(values, Mapping)
        }

        group_payload = _read_json(str(Path(group_data_path).resolve()))
        pure_payload = _read_json(str(Path(pure_data_path).resolve()))
        self._subgroups = self._load_subgroups(group_payload)
        self._interactions = self._load_interactions(group_payload)
        pure_records = self._load_pure_records(pure_payload)
        self.components = component_ids
        self._component_data = tuple(
            self._component_from_record(
                cas,
                pure_records,
                self._subgroups,
                fallbacks.get(cas),
            )
            for cas in component_ids
        )
        self.component_parameter_sources = {
            component.cas: component.parameter_source
            for component in self._component_data
        }
        self._validate_required_interactions()
        self._mixture_parameter_cache: dict[tuple, _MixtureParameters] = {}
        try:
            if __package__ and __package__.split('.', 1)[0] == 'pfdsim':
                from ..compiled_psrk import CompiledPSRKBackend
            else:
                from compiled_psrk import CompiledPSRKBackend

            self._compiled_backend = CompiledPSRKBackend.from_psrk(self)
        except Exception:
            self._compiled_backend = None

    def add_warning(self, message: str) -> None:
        text = str(message).strip()
        if not text or text in self._warning_keys:
            return
        self._warning_keys.add(text)
        self.warnings.append(text)

    @staticmethod
    def _load_subgroups(payload: dict) -> dict[int, _Subgroup]:
        records = payload.get("subgroups")
        if not isinstance(records, list) or not records:
            raise PSRKDataError("PSRK group JSON has no subgroup records")
        subgroups: dict[int, _Subgroup] = {}
        for index, record in enumerate(records, start=1):
            if not isinstance(record, dict):
                raise PSRKDataError(f"PSRK subgroup record {index} is not an object")
            try:
                subgroup_id = int(record["subgroup_id"])
                main_group_id = int(record["main_group_id"])
            except (KeyError, TypeError, ValueError) as error:
                raise PSRKDataError(f"Invalid PSRK subgroup indices in record {index}") from error
            if subgroup_id in subgroups:
                raise PSRKDataError(f"Duplicate PSRK subgroup ID {subgroup_id}")
            subgroups[subgroup_id] = _Subgroup(
                subgroup_id=subgroup_id,
                main_group_id=main_group_id,
                R=_finite(record.get("R"), f"subgroup {subgroup_id} R"),
                Q=_finite(record.get("Q"), f"subgroup {subgroup_id} Q"),
            )
        return subgroups

    @staticmethod
    def _load_interactions(
        payload: dict,
    ) -> dict[tuple[int, int], tuple[float, float, float]]:
        records = payload.get("interactions")
        if not isinstance(records, list) or not records:
            raise PSRKDataError("PSRK group JSON has no interaction records")
        interactions: dict[tuple[int, int], tuple[float, float, float]] = {}
        for index, record in enumerate(records, start=1):
            if not isinstance(record, dict):
                raise PSRKDataError(f"PSRK interaction record {index} is not an object")
            try:
                group_i = int(record["main_group_i"])
                group_j = int(record["main_group_j"])
                directions = (
                    (group_i, group_j, record["i_to_j"]),
                    (group_j, group_i, record["j_to_i"]),
                )
            except (KeyError, TypeError, ValueError) as error:
                raise PSRKDataError(f"Invalid PSRK interaction record {index}") from error
            for source, target, coefficients in directions:
                key = (source, target)
                if key in interactions:
                    raise PSRKDataError(f"Duplicate directed PSRK interaction {key}")
                if not isinstance(coefficients, dict):
                    raise PSRKDataError(f"Invalid coefficients for PSRK interaction {key}")
                interactions[key] = (
                    _finite(coefficients.get("a_K"), f"interaction {key} a"),
                    _finite(coefficients.get("b"), f"interaction {key} b"),
                    _finite(coefficients.get("c_per_K"), f"interaction {key} c"),
                )
        return interactions

    @staticmethod
    def _load_pure_records(payload: dict) -> dict[str, dict]:
        records = payload.get("components")
        if not isinstance(records, list) or not records:
            raise PSRKDataError("PSRK pure-component JSON has no component records")
        by_cas: dict[str, dict] = {}
        for index, record in enumerate(records, start=1):
            if not isinstance(record, dict):
                raise PSRKDataError(f"PSRK pure-component record {index} is not an object")
            cas = str(record.get("CAS") or "").strip()
            if not cas:
                raise PSRKDataError(f"PSRK pure-component record {index} has no CAS number")
            if cas in by_cas:
                raise PSRKDataError(f"Duplicate PSRK pure-component CAS number {cas}")
            by_cas[cas] = record
        return by_cas

    def _component_from_record(
        self,
        cas: str,
        pure_records: dict[str, dict],
        subgroups: dict[int, _Subgroup],
        fallback: Mapping[str, Any] | None,
    ) -> _Component:
        record = pure_records.get(cas)
        if record is None:
            raise PSRKUnsupportedComponentError(
                f"No published 2005 PSRK pure-component record for CAS {cas}"
            )
        estimated_fields = [
            field
            for field, flag in (
                ("Tc", record.get("Tc_estimated")),
                ("Pc", record.get("Pc_estimated")),
            )
            if bool(flag)
        ]
        missing_bundle_fields: list[str] = []
        for field, value in (
            ("Tc", record.get("Tc_K")),
            ("Pc", record.get("Pc_kPa")),
        ):
            try:
                numeric = float(value)
            except (TypeError, ValueError):
                numeric = math.nan
            if not math.isfinite(numeric) or numeric <= 0.0:
                missing_bundle_fields.append(field)
        try:
            record_omega = float(record.get("omega"))
        except (TypeError, ValueError):
            record_omega = math.nan
        if not math.isfinite(record_omega):
            missing_bundle_fields.append("omega")
        if not isinstance(record.get("mathias_copeman"), dict):
            missing_bundle_fields.append("Mathias-Copeman parameters")
        raw_assignments = record.get("subgroups")
        if not isinstance(raw_assignments, list) or not raw_assignments:
            raise PSRKUnsupportedComponentError(
                f"PSRK component {cas} has no complete published subgroup assignment"
            )
        assignments: list[tuple[int, int]] = []
        seen: set[int] = set()
        r_value = 0.0
        q_value = 0.0
        for assignment in raw_assignments:
            if not isinstance(assignment, dict):
                raise PSRKDataError(f"Invalid subgroup assignment for PSRK component {cas}")
            try:
                subgroup_id = int(assignment["subgroup_id"])
                count = int(assignment["count"])
            except (KeyError, TypeError, ValueError) as error:
                raise PSRKDataError(
                    f"Invalid subgroup assignment for PSRK component {cas}"
                ) from error
            if count <= 0 or subgroup_id in seen:
                raise PSRKDataError(
                    f"Invalid or duplicate subgroup {subgroup_id} for PSRK component {cas}"
                )
            subgroup = subgroups.get(subgroup_id)
            if subgroup is None:
                raise PSRKDataError(
                    f"PSRK component {cas} references unknown subgroup {subgroup_id}"
                )
            seen.add(subgroup_id)
            assignments.append((subgroup_id, count))
            r_value += count * subgroup.R
            q_value += count * subgroup.Q

        if r_value <= 0.0 or q_value <= 0.0:
            raise PSRKDataError(f"PSRK component {cas} has nonpositive UNIFAC r or q")

        use_fallback = bool(estimated_fields or missing_bundle_fields) or bool(
            fallback and fallback.get("override_bundle")
        )
        if use_fallback:
            if not fallback:
                reason = (
                    f"estimated {'/'.join(estimated_fields)}"
                    if estimated_fields
                    else (
                        f"missing {'/'.join(missing_bundle_fields)}"
                        if missing_bundle_fields
                        else "an explicit bundle override"
                    )
                )
                raise PSRKUnsupportedComponentError(
                    f"PSRK component {cas} requires resolved Tc/Pc/omega because "
                    f"the 2005 table has {reason}, but no fallback was supplied"
                )
            Tc_K = _positive_finite(
                fallback.get("Tc_K"), f"PSRK fallback component {cas} Tc"
            )
            Pc_bar = _positive_finite(
                fallback.get("Pc_bar"), f"PSRK fallback component {cas} Pc"
            )
            omega = _finite(
                fallback.get("omega"), f"PSRK fallback component {cas} omega"
            )
            uses_mathias_copeman = fallback.get("mc_c1") is not None
            if uses_mathias_copeman:
                c1 = _finite(
                    fallback.get("mc_c1"), f"PSRK fallback component {cas} c1"
                )
                c2 = _finite(
                    fallback.get("mc_c2", 0.0) or 0.0,
                    f"PSRK fallback component {cas} c2",
                )
                c3 = _finite(
                    fallback.get("mc_c3", 0.0) or 0.0,
                    f"PSRK fallback component {cas} c3",
                )
            else:
                c1 = c2 = c3 = 0.0
            Tmin_K = fallback.get("mc_Tmin_K")
            Tmax_K = fallback.get("mc_Tmax_K")
            parameter_source = str(
                fallback.get("source") or "resolved critical-property fallback"
            )
            alpha_description = (
                "explicit Mathias-Copeman alpha"
                if uses_mathias_copeman
                else "generalized omega-based Soave alpha"
            )
            self.add_warning(
                f"PSRK component {cas} uses {parameter_source} Tc/Pc/omega and "
                f"{alpha_description} instead of the complete published PSRK bundle."
            )
        else:
            Tc_K = _positive_finite(record.get("Tc_K"), f"PSRK component {cas} Tc")
            Pc_bar = (
                _positive_finite(record.get("Pc_kPa"), f"PSRK component {cas} Pc")
                / 100.0
            )
            omega = _finite(record.get("omega"), f"PSRK component {cas} omega")
            mc = record.get("mathias_copeman")
            if not isinstance(mc, dict):
                raise PSRKDataError(
                    f"PSRK component {cas} has no Mathias-Copeman parameters"
                )
            c1 = _finite(mc.get("c1"), f"PSRK component {cas} c1")
            c2 = _finite(mc.get("c2"), f"PSRK component {cas} c2")
            c3 = _finite(mc.get("c3"), f"PSRK component {cas} c3")
            Tmin_K = mc.get("Tmin_K")
            Tmax_K = mc.get("Tmax_K")
            uses_mathias_copeman = True
            parameter_source = "PSRK 2005 published pure-component bundle"

        Tmin = None if Tmin_K is None else _positive_finite(Tmin_K, f"PSRK component {cas} Tmin")
        Tmax = None if Tmax_K is None else _positive_finite(Tmax_K, f"PSRK component {cas} Tmax")
        if Tmin is not None and Tmax is not None and Tmin > Tmax:
            raise PSRKDataError(f"PSRK component {cas} has Tmin above Tmax")

        return _Component(
            cas=cas,
            name=str(record.get("name") or cas),
            Tc_K=Tc_K,
            Pc_bar=Pc_bar,
            omega=omega,
            uses_mathias_copeman=uses_mathias_copeman,
            c1=c1,
            c2=c2,
            c3=c3,
            Tmin_K=Tmin,
            Tmax_K=Tmax,
            subgroups=tuple(assignments),
            r=r_value,
            q=q_value,
            a0=SRK_OMEGA_A * R_BAR_CM3_PER_MOL_K**2 * Tc_K**2 / Pc_bar,
            b=SRK_OMEGA_B * R_BAR_CM3_PER_MOL_K * Tc_K / Pc_bar,
            parameter_source=parameter_source,
        )

    def _validate_required_interactions(self) -> None:
        main_groups = {
            self._subgroups[subgroup_id].main_group_id
            for component in self._component_data
            for subgroup_id, _ in component.subgroups
        }
        missing = [
            (source, target)
            for source in sorted(main_groups)
            for target in sorted(main_groups)
            if source != target and (source, target) not in self._interactions
        ]
        if missing:
            preview = ", ".join(f"{source}->{target}" for source, target in missing[:12])
            if len(missing) > 12:
                preview += f", ... (+{len(missing) - 12} more)"
            raise PSRKDataError(
                f"Published PSRK interaction parameters are missing for {preview}"
            )

    @staticmethod
    def _normalize_phase(phase: str) -> str:
        normalized = str(phase).strip().lower()
        if normalized in {"vapor", "vap", "gas"}:
            return "vapor"
        if normalized in {"liquid", "liq"}:
            return "liquid"
        raise PSRKCalculationError("PSRK phase must be 'vapor' or 'liquid'")

    def _normalize_composition(self, composition: Mapping[str, float]) -> tuple[float, ...]:
        if not isinstance(composition, Mapping):
            raise PSRKCalculationError("PSRK composition must be a CAS-keyed mapping")
        unknown = sorted(set(composition) - set(self.components))
        if unknown:
            raise PSRKCalculationError(
                f"PSRK composition contains unknown components: {', '.join(unknown)}"
            )
        values: list[float] = []
        for cas in self.components:
            try:
                value = float(composition.get(cas, 0.0))
            except (TypeError, ValueError) as error:
                raise PSRKCalculationError(f"Invalid mole fraction for {cas}") from error
            if not math.isfinite(value) or value < 0.0:
                raise PSRKCalculationError(
                    f"Mole fraction for {cas} must be finite and nonnegative"
                )
            values.append(value)
        total = sum(values)
        if total <= 0.0:
            raise PSRKCalculationError("PSRK composition has no positive mole fractions")
        return tuple(value / total for value in values)

    @staticmethod
    def _validate_temperature_pressure(
        T_K: float,
        P_bar: float,
    ) -> tuple[float, float]:
        try:
            temperature = float(T_K)
            pressure = float(P_bar)
        except (TypeError, ValueError) as error:
            raise PSRKCalculationError(
                "PSRK temperature and pressure must be numeric"
            ) from error
        if not math.isfinite(temperature) or temperature <= 0.0:
            raise PSRKCalculationError(
                "PSRK temperature must be positive and finite"
            )
        if not math.isfinite(pressure) or pressure <= 0.0:
            raise PSRKCalculationError(
                "PSRK pressure must be positive and finite"
            )
        return temperature, pressure

    @staticmethod
    def _alpha(component: _Component, T_K: float) -> float:
        alpha, _ = PSRK._alpha_and_derivative(component, T_K)
        return alpha

    @staticmethod
    def _alpha_and_derivative(component: _Component, T_K: float) -> tuple[float, float]:
        """Return the selected SRK alpha and its temperature derivative."""
        reduced_temperature = T_K / component.Tc_K
        sqrt_reduced_temperature = math.sqrt(reduced_temperature)
        theta = 1.0 - sqrt_reduced_temperature
        dtheta_dT = -sqrt_reduced_temperature / (2.0 * T_K)
        if not component.uses_mathias_copeman:
            coefficient = (
                0.48
                + 1.574 * component.omega
                - 0.176 * component.omega * component.omega
            )
            factor = 1.0 + coefficient * theta
            dfactor_dtheta = coefficient
        elif reduced_temperature <= 1.0:
            factor = (
                1.0
                + component.c1 * theta
                + component.c2 * theta**2
                + component.c3 * theta**3
            )
            dfactor_dtheta = (
                component.c1
                + 2.0 * component.c2 * theta
                + 3.0 * component.c3 * theta**2
            )
        else:
            # Published Mathias-Copeman supercritical continuation.
            factor = 1.0 + component.c1 * theta
            dfactor_dtheta = component.c1
        alpha = factor * factor
        dalpha_dT = 2.0 * factor * dfactor_dtheta * dtheta_dT
        return alpha, dalpha_dT

    def _interaction_factor(self, source: int, target: int, T_K: float) -> float:
        factor, _ = self._interaction_factor_and_derivative(source, target, T_K)
        return factor

    def _interaction_factor_and_derivative(
        self,
        source: int,
        target: int,
        T_K: float,
    ) -> tuple[float, float]:
        """Return a PSRK group interaction factor and its temperature derivative."""
        if source == target:
            return 1.0, 0.0
        coefficients = self._interactions.get((source, target))
        if coefficients is None:
            raise PSRKDataError(f"Missing PSRK interaction {source}->{target}")
        a_value, b_value, c_value = coefficients
        exponent = -(a_value + b_value * T_K + c_value * T_K * T_K) / T_K
        try:
            result = math.exp(exponent)
        except OverflowError as error:
            raise PSRKCalculationError(
                f"PSRK interaction {source}->{target} overflows at {T_K:g} K"
            ) from error
        if not math.isfinite(result) or result <= 0.0:
            raise PSRKCalculationError(
                f"Invalid PSRK interaction factor {source}->{target} at {T_K:g} K"
            )
        derivative = result * (a_value / (T_K * T_K) - c_value)
        if not math.isfinite(derivative):
            raise PSRKCalculationError(
                f"Invalid PSRK interaction derivative {source}->{target} at {T_K:g} K"
            )
        return result, derivative

    def _group_ln_activity(
        self,
        group_amounts: Mapping[int, float],
        T_K: float,
    ) -> dict[int, float]:
        values, _ = self._group_ln_activity_and_derivative(group_amounts, T_K)
        return values

    def _group_ln_activity_and_derivative(
        self,
        group_amounts: Mapping[int, float],
        T_K: float,
    ) -> tuple[dict[int, float], dict[int, float]]:
        total_groups = sum(group_amounts.values())
        if total_groups <= 0.0:
            raise PSRKCalculationError("PSRK UNIFAC group mixture is empty")
        group_fractions = {
            subgroup_id: amount / total_groups
            for subgroup_id, amount in group_amounts.items()
            if amount > 0.0
        }
        surface_total = sum(
            self._subgroups[subgroup_id].Q * fraction
            for subgroup_id, fraction in group_fractions.items()
        )
        if surface_total <= 0.0:
            raise PSRKCalculationError("PSRK UNIFAC group surface total is nonpositive")
        theta = {
            subgroup_id: self._subgroups[subgroup_id].Q * fraction / surface_total
            for subgroup_id, fraction in group_fractions.items()
        }

        psi: dict[tuple[int, int], float] = {}
        dpsi_dT: dict[tuple[int, int], float] = {}
        for subgroup_m in group_fractions:
            main_m = self._subgroups[subgroup_m].main_group_id
            for subgroup_n in group_fractions:
                main_n = self._subgroups[subgroup_n].main_group_id
                factor, derivative = self._interaction_factor_and_derivative(
                    main_m, main_n, T_K
                )
                psi[subgroup_m, subgroup_n] = factor
                dpsi_dT[subgroup_m, subgroup_n] = derivative
        denominators = {
            subgroup_m: sum(
                theta[subgroup_n] * psi[subgroup_n, subgroup_m]
                for subgroup_n in group_fractions
            )
            for subgroup_m in group_fractions
        }
        if any(value <= 0.0 for value in denominators.values()):
            raise PSRKCalculationError("PSRK UNIFAC group denominator is nonpositive")
        denominator_derivatives = {
            subgroup_m: sum(
                theta[subgroup_n] * dpsi_dT[subgroup_n, subgroup_m]
                for subgroup_n in group_fractions
            )
            for subgroup_m in group_fractions
        }

        result: dict[int, float] = {}
        derivative_result: dict[int, float] = {}
        for subgroup_k in group_fractions:
            term2 = sum(
                theta[subgroup_m]
                * psi[subgroup_k, subgroup_m]
                / denominators[subgroup_m]
                for subgroup_m in group_fractions
            )
            result[subgroup_k] = self._subgroups[subgroup_k].Q * (
                1.0 - math.log(denominators[subgroup_k]) - term2
            )
            derivative_term2 = sum(
                theta[subgroup_m]
                * (
                    dpsi_dT[subgroup_k, subgroup_m] / denominators[subgroup_m]
                    - psi[subgroup_k, subgroup_m]
                    * denominator_derivatives[subgroup_m]
                    / (denominators[subgroup_m] ** 2)
                )
                for subgroup_m in group_fractions
            )
            derivative_result[subgroup_k] = self._subgroups[subgroup_k].Q * (
                -denominator_derivatives[subgroup_k] / denominators[subgroup_k]
                - derivative_term2
            )
        return result, derivative_result

    def _ln_activity_coefficients(
        self,
        composition: tuple[float, ...],
        T_K: float,
    ) -> tuple[float, ...]:
        values, _ = self._ln_activity_coefficients_and_derivative(composition, T_K)
        return values

    def excess_gibbs_state(
        self,
        composition: tuple[float, ...],
        T_K: float,
    ) -> ExcessGibbsState:
        """Return the PSRK-UNIFAC state consumed by the gE-EOS mixing rule."""
        values, derivatives = self._ln_activity_coefficients_and_derivative(
            composition, T_K
        )
        return ExcessGibbsState(values, derivatives)

    def _ln_activity_coefficients_and_derivative(
        self,
        composition: tuple[float, ...],
        T_K: float,
    ) -> tuple[tuple[float, ...], tuple[float, ...]]:
        sum_xr = sum(
            mole_fraction * component.r
            for mole_fraction, component in zip(composition, self._component_data)
        )
        sum_xq = sum(
            mole_fraction * component.q
            for mole_fraction, component in zip(composition, self._component_data)
        )
        if sum_xr <= 0.0 or sum_xq <= 0.0:
            raise PSRKCalculationError("PSRK UNIFAC mixture r or q is nonpositive")

        z_half = 0.5 * UNIFAC_COORDINATION_NUMBER
        ell = tuple(
            z_half * (component.r - component.q) - (component.r - 1.0)
            for component in self._component_data
        )
        sum_x_ell = sum(
            mole_fraction * ell_value
            for mole_fraction, ell_value in zip(composition, ell)
        )
        combinatorial: list[float] = []
        for component, ell_value in zip(self._component_data, ell):
            phi_over_x = component.r / sum_xr
            theta_over_phi = component.q * sum_xr / (component.r * sum_xq)
            combinatorial.append(
                math.log(phi_over_x)
                + z_half * component.q * math.log(theta_over_phi)
                + ell_value
                - phi_over_x * sum_x_ell
            )

        mixture_groups: dict[int, float] = {}
        for mole_fraction, component in zip(composition, self._component_data):
            for subgroup_id, count in component.subgroups:
                mixture_groups[subgroup_id] = (
                    mixture_groups.get(subgroup_id, 0.0) + mole_fraction * count
                )
        mixture_group_activity, mixture_group_derivative = (
            self._group_ln_activity_and_derivative(mixture_groups, T_K)
        )

        residual: list[float] = []
        residual_derivative: list[float] = []
        for component in self._component_data:
            pure_groups = dict(component.subgroups)
            pure_group_activity, pure_group_derivative = (
                self._group_ln_activity_and_derivative(pure_groups, T_K)
            )
            residual.append(sum(
                count
                * (
                    mixture_group_activity.get(subgroup_id, 0.0)
                    - pure_group_activity[subgroup_id]
                )
                for subgroup_id, count in component.subgroups
            ))
            residual_derivative.append(sum(
                count
                * (
                    mixture_group_derivative.get(subgroup_id, 0.0)
                    - pure_group_derivative[subgroup_id]
                )
                for subgroup_id, count in component.subgroups
            ))
        values = tuple(
            combinatorial_value + residual_value
            for combinatorial_value, residual_value in zip(combinatorial, residual)
        )
        return values, tuple(residual_derivative)

    def _mixture_parameters(
        self,
        T_K: float,
        composition: tuple[float, ...],
    ) -> _MixtureParameters:
        key = (float(T_K), tuple(composition))
        cached = self._mixture_parameter_cache.get(key)
        if cached is not None:
            return cached

        if self._compiled_backend is not None:
            pure_a, pure_d, b_mix, D, dD_dT, sigma = (
                self._compiled_backend.mixture_parameters(T_K, composition)
            )
            mixture = _MixtureParameters(
                composition=tuple(composition),
                pure_a=tuple(float(value) for value in pure_a),
                pure_d=tuple(float(value) for value in pure_d),
                b=float(b_mix),
                D=float(D),
                dD_dT=float(dD_dT),
                sigma=tuple(float(value) for value in sigma),
            )
        else:
            mixture = self._mixture_parameters_reference(T_K, composition)

        if len(self._mixture_parameter_cache) > 50000:
            self._mixture_parameter_cache.clear()
        self._mixture_parameter_cache[key] = mixture
        return mixture

    def _mixture_parameters_reference(
        self,
        T_K: float,
        composition: tuple[float, ...],
    ) -> _MixtureParameters:
        """Readable Python reference for the compiled numerical kernel."""
        alpha_and_derivative = tuple(
            self._alpha_and_derivative(component, T_K)
            for component in self._component_data
        )
        pure_a = tuple(
            component.a0 * alpha
            for component, (alpha, _) in zip(self._component_data, alpha_and_derivative)
        )
        pure_da_dT = tuple(
            component.a0 * derivative
            for component, (_, derivative) in zip(
                self._component_data, alpha_and_derivative
            )
        )
        pure_d = tuple(
            a_value / (component.b * R_BAR_CM3_PER_MOL_K * T_K)
            for a_value, component in zip(pure_a, self._component_data)
        )
        pure_dd_dT = tuple(
            da_value / (component.b * R_BAR_CM3_PER_MOL_K * T_K)
            - d_value / T_K
            for da_value, d_value, component in zip(
                pure_da_dT, pure_d, self._component_data
            )
        )
        excess = self.excess_gibbs_state(composition, T_K)
        try:
            mixing = self._mixing_rule.mix(
                composition,
                tuple(component.b for component in self._component_data),
                pure_d,
                pure_dd_dT,
                excess,
            )
        except ValueError as error:
            raise PSRKCalculationError(f"Invalid PSRK mixing state: {error}") from error
        return _MixtureParameters(
            composition=composition,
            pure_a=pure_a,
            pure_d=pure_d,
            b=mixing.b,
            D=mixing.D,
            dD_dT=mixing.dD_dT,
            sigma=mixing.composition_derivatives,
        )

    @staticmethod
    def _cbrt(value: float) -> float:
        return math.copysign(abs(value) ** (1.0 / 3.0), value)

    @classmethod
    def _solve_monic_cubic(cls, a: float, b: float, c: float) -> list[float]:
        """Return the real roots of z^3 + a*z^2 + b*z + c = 0."""
        p = b - a * a / 3.0
        q = 2.0 * a**3 / 27.0 - a * b / 3.0 + c
        shift = a / 3.0
        discriminant = (0.5 * q) ** 2 + (p / 3.0) ** 3
        tolerance = 1.0e-14
        if discriminant > tolerance:
            root = (
                cls._cbrt(-0.5 * q + math.sqrt(discriminant))
                + cls._cbrt(-0.5 * q - math.sqrt(discriminant))
            )
            return [root - shift]
        if abs(p) < tolerance:
            return [-shift]
        argument = (3.0 * q / (2.0 * p)) * math.sqrt(-3.0 / p)
        argument = max(-1.0, min(1.0, argument))
        theta = math.acos(argument)
        radius = 2.0 * math.sqrt(-p / 3.0)
        return [
            radius * math.cos((theta + 2.0 * math.pi * index) / 3.0) - shift
            for index in range(3)
        ]

    @classmethod
    def _compressibility_roots(cls, A: float, B: float) -> list[float]:
        roots = cls._solve_monic_cubic(
            -1.0,
            A - B - B * B,
            -A * B,
        )
        physical = sorted(root for root in roots if root > B + 1.0e-12)
        if not physical:
            raise PSRKCalculationError("PSRK SRK cubic has no physical compressibility root")
        return physical

    def _validated_state(
        self,
        T_K: float,
        P_bar: float,
        composition: Mapping[str, float],
        phase: str,
    ) -> tuple[float, tuple[float, ...], _MixtureParameters, float, float]:
        temperature, pressure = self._validate_temperature_pressure(T_K, P_bar)
        normalized_phase = self._normalize_phase(phase)
        normalized_composition = self._normalize_composition(composition)
        mixture = self._mixture_parameters(temperature, normalized_composition)
        B = mixture.b * pressure / (R_BAR_CM3_PER_MOL_K * temperature)
        roots = self._compressibility_roots(mixture.D * B, B)
        Z = roots[-1] if normalized_phase == "vapor" else roots[0]
        if Z <= B:
            raise PSRKCalculationError("PSRK selected root does not exceed B")
        return temperature, normalized_composition, mixture, B, Z

    def compressibility_roots(
        self,
        T_K: float,
        P_bar: float,
        composition: Mapping[str, float],
    ) -> list[float]:
        """Return all physical PSRK compressibility roots."""
        if self._compiled_backend is not None:
            temperature, pressure = self._validate_temperature_pressure(
                T_K, P_bar
            )
            normalized = self._normalize_composition(composition)
            return [
                float(value)
                for value in self._compiled_backend.compressibility_roots(
                    temperature, pressure, normalized
                )
            ]
        temperature, normalized, mixture, B, _ = self._validated_state(
            T_K, P_bar, composition, "vapor"
        )
        del temperature, normalized
        return self._compressibility_roots(mixture.D * B, B)

    def compressibility_factor(
        self,
        T_K: float,
        P_bar: float,
        composition: Mapping[str, float],
        phase: str = "vapor",
    ) -> float:
        """Return the selected PSRK compressibility factor."""
        return self._validated_state(T_K, P_bar, composition, phase)[-1]

    def molar_volume(
        self,
        T_K: float,
        P_bar: float,
        composition: Mapping[str, float],
        phase: str = "vapor",
    ) -> float:
        """Return un-translated EOS molar volume [cm3/mol]."""
        temperature, _, _, _, Z = self._validated_state(
            T_K, P_bar, composition, phase
        )
        return Z * R_BAR_CM3_PER_MOL_K * temperature / float(P_bar)

    def _wilson_K(self, T_K: float, P_bar: float) -> dict[str, float]:
        result = {}
        for component in self._component_data:
            exponent = 5.373 * (1.0 + component.omega) * (
                1.0 - component.Tc_K / T_K
            )
            result[component.cas] = max(
                1.0e-8,
                min(
                    1.0e8,
                    component.Pc_bar / P_bar * math.exp(exponent),
                ),
            )
        return result

    def phi_phi_K_values(
        self,
        T_K: float,
        P_bar: float,
        liquid_composition: Mapping[str, float],
        max_iter: int = 80,
    ) -> dict[str, float]:
        """Return composition-dependent PSRK phi-phi equilibrium ratios."""
        temperature, pressure = self._validate_temperature_pressure(T_K, P_bar)
        x_values = self._normalize_composition(liquid_composition)
        x = dict(zip(self.components, x_values))
        cache_key = (
            temperature,
            pressure,
            tuple(x_values),
            int(max_iter),
        )
        cached = self._phi_phi_k_cache.get(cache_key)
        if cached is not None:
            return dict(cached)

        if self._compiled_backend is not None:
            values = self._compiled_backend.phi_phi_K_values(
                temperature, pressure, x_values, int(max_iter)
            )
            result = {
                cas: float(value)
                for cas, value in zip(self.components, values)
            }
            return self._set_cached_phi_phi_K(cache_key, result)

        K = self._wilson_K(temperature, pressure)
        if len(self.compressibility_roots(T_K, P_bar, x)) < 2:
            return self._set_cached_phi_phi_K(cache_key, K)
        phi_liquid = self.fugacity_coefficients(T_K, P_bar, x, "liquid")
        y_values = self._normalize_composition({
            cas: x[cas] * K[cas] for cas in self.components
        })
        y = dict(zip(self.components, y_values))

        for _ in range(max_iter):
            if len(self.compressibility_roots(T_K, P_bar, y)) < 2:
                return self._set_cached_phi_phi_K(cache_key, K)
            phi_vapor = self.fugacity_coefficients(T_K, P_bar, y, "vapor")
            K_new = {
                cas: max(
                    1.0e-8,
                    min(1.0e8, phi_liquid[cas] / phi_vapor[cas]),
                )
                for cas in self.components
            }
            new_y_values = self._normalize_composition({
                cas: x[cas] * K_new[cas] for cas in self.components
            })
            new_y = dict(zip(self.components, new_y_values))
            if max(
                abs(new_y[cas] - y[cas]) for cas in self.components
            ) < 1.0e-9:
                return self._set_cached_phi_phi_K(cache_key, K_new)
            K = {
                cas: 0.5 * K[cas] + 0.5 * K_new[cas]
                for cas in self.components
            }
            y = new_y
        return self._set_cached_phi_phi_K(cache_key, K)

    def _set_cached_phi_phi_K(
        self,
        key: tuple,
        values: dict[str, float],
    ) -> dict[str, float]:
        if len(self._phi_phi_k_cache) > 20000:
            self._phi_phi_k_cache.clear()
        self._phi_phi_k_cache[key] = dict(values)
        return dict(values)

    def departure_enthalpy(
        self,
        T_K: float,
        P_bar: float,
        composition: Mapping[str, float],
        phase: str = "vapor",
    ) -> float:
        """Return molar departure enthalpy ``H-H_ideal`` [kJ/kmol]."""
        if self._compiled_backend is not None:
            temperature, pressure = self._validate_temperature_pressure(
                T_K, P_bar
            )
            normalized_phase = self._normalize_phase(phase)
            normalized = self._normalize_composition(composition)
            return self._compiled_backend.departure_enthalpy(
                temperature, pressure, normalized, normalized_phase
            )
        temperature, _, mixture, B, Z = self._validated_state(
            T_K, P_bar, composition, phase
        )
        attraction_log = math.log1p(B / Z)
        value_bar_cm3_per_mol = R_BAR_CM3_PER_MOL_K * temperature * (Z - 1.0)
        value_bar_cm3_per_mol += (
            R_BAR_CM3_PER_MOL_K
            * temperature
            * temperature
            * mixture.dD_dT
            * attraction_log
        )
        return 0.1 * value_bar_cm3_per_mol

    def departure_entropy(
        self,
        T_K: float,
        P_bar: float,
        composition: Mapping[str, float],
        phase: str = "vapor",
    ) -> float:
        """Return molar departure entropy ``S-S_ideal`` [kJ/kmol/K]."""
        temperature, _, mixture, B, Z = self._validated_state(
            T_K, P_bar, composition, phase
        )
        attraction_log = math.log1p(B / Z)
        value_bar_cm3_per_mol_K = R_BAR_CM3_PER_MOL_K * math.log(Z - B)
        value_bar_cm3_per_mol_K += (
            R_BAR_CM3_PER_MOL_K
            * (mixture.D + temperature * mixture.dD_dT)
            * attraction_log
        )
        return 0.1 * value_bar_cm3_per_mol_K

    def departure_gibbs(
        self,
        T_K: float,
        P_bar: float,
        composition: Mapping[str, float],
        phase: str = "vapor",
    ) -> float:
        """Return molar departure Gibbs energy ``G-G_ideal`` [kJ/kmol]."""
        enthalpy = self.departure_enthalpy(T_K, P_bar, composition, phase)
        entropy = self.departure_entropy(T_K, P_bar, composition, phase)
        return enthalpy - float(T_K) * entropy

    def departure_heat_capacity(
        self,
        T_K: float,
        P_bar: float,
        composition: Mapping[str, float],
        phase: str = "vapor",
    ) -> float:
        """Return constant-pressure departure heat capacity [kJ/kmol/K].

        This is the centered temperature derivative of the analytical
        departure enthalpy at fixed pressure, composition, and selected phase.
        """
        try:
            temperature = float(T_K)
        except (TypeError, ValueError) as error:
            raise PSRKCalculationError("PSRK temperature must be numeric") from error
        if not math.isfinite(temperature) or temperature <= 0.0:
            raise PSRKCalculationError("PSRK temperature must be positive and finite")
        step = max(0.05, 1.0e-4 * temperature)
        lower_temperature = max(0.5 * temperature, temperature - step)
        upper_temperature = temperature + step
        lower = self.departure_enthalpy(
            lower_temperature, P_bar, composition, phase
        )
        upper = self.departure_enthalpy(
            upper_temperature, P_bar, composition, phase
        )
        return (upper - lower) / (upper_temperature - lower_temperature)

    def fugacity_coefficients(
        self,
        T_K: float,
        P_bar: float,
        composition: Mapping[str, float],
        phase: str = "vapor",
    ) -> dict[str, float]:
        """Return PSRK fugacity coefficients for a mixture state.

        Parameters use kelvin, bar, and mole fractions.  ``phase='vapor'``
        selects the largest physical SRK root; ``phase='liquid'`` selects the
        smallest.  With one physical root both phase labels return that root.
        """
        if self._compiled_backend is not None:
            temperature, pressure = self._validate_temperature_pressure(
                T_K, P_bar
            )
            normalized_phase = self._normalize_phase(phase)
            normalized = self._normalize_composition(composition)
            values = self._compiled_backend.fugacity_coefficients(
                temperature, pressure, normalized, normalized_phase
            )
            result = {
                cas: float(value)
                for cas, value in zip(self.components, values)
            }
            if any(
                not math.isfinite(value) or value <= 0.0
                for value in result.values()
            ):
                raise PSRKCalculationError(
                    "PSRK compiled fugacity coefficient is invalid"
                )
            return result
        temperature, _, mixture, B, Z = self._validated_state(
            T_K, P_bar, composition, phase
        )
        attraction_log = math.log1p(B / Z)

        result: dict[str, float] = {}
        for cas, component, sigma_i in zip(
            self.components, self._component_data, mixture.sigma
        ):
            ln_phi = (
                (component.b / mixture.b) * (Z - 1.0)
                - math.log(Z - B)
                - sigma_i * attraction_log
            )
            try:
                phi = math.exp(ln_phi)
            except OverflowError as error:
                raise PSRKCalculationError(
                    f"PSRK fugacity coefficient overflows for {cas}"
                ) from error
            if not math.isfinite(phi) or phi <= 0.0:
                raise PSRKCalculationError(
                    f"PSRK fugacity coefficient is invalid for {cas}"
                )
            result[cas] = phi
        return result
